import type { StackProfile } from "./stack.js";

/** Sentinel marking a generated gate. Used for hand-edit protection in writeTunedGate. */
export const GENERATED_MARKER = "@generated by backpressure gate";

const HEADER = `#!/usr/bin/env bash
# ${GENERATED_MARKER} — edits are overwritten; re-run 'backpressure gate' to retune.
# Composite gate: fail-fast, ONE exit code.
set -euo pipefail
`;

// Lang-agnostic, tool-guarded so a fresh project still runs the gate out of the box.
const SECRET_SCAN = `
echo "== secret scan =="
if command -v gitleaks >/dev/null 2>&1; then
  gitleaks detect --no-banner --redact
else
  echo "  (gitleaks not installed — skipping secret scan)"
fi
`;

const GREEN = `\necho "gate: GREEN"\n`;

function rustStages(): string {
  return [
    `\necho "== 1. format =="\ncargo fmt --check`,
    `\necho "== 2. lint =="\ncargo clippy --all-targets -- -D warnings`,
    `\necho "== 3. test =="\ncargo test`,
    `\necho "== 4. build =="\ncargo build`,
  ].join("");
}

function nodeStages(p: StackProfile): string {
  const pm = p.pm ?? "npm";
  const out: string[] = [];
  if (p.linter === "biome") out.push(`\necho "== 1. lint =="\n${pm} exec biome check .`);
  else if (p.linter === "eslint") out.push(`\necho "== 1. lint =="\n${pm} exec eslint .`);
  else out.push(`\necho "== 1. lint (skipped — no biome/eslint detected) =="`);
  if (p.hasTsconfig) out.push(`\necho "== 2. typecheck =="\n${pm} exec tsc --noEmit`);
  out.push(`\necho "== 3. test =="\n${pm} test`);
  if (p.hasBuildScript) out.push(`\necho "== 4. build =="\n${pm} run build`);
  return out.join("");
}

const UNKNOWN_BANNER = `
# ┌───────────────────────────────────────────────────────────────────────────┐
# │  ⚠  TUNE THIS GATE TO YOUR STACK. Backpressure could not detect a Rust or    │
# │  Node project, so this is a generic pnpm/TypeScript pipeline. Edit the       │
# │  stages for your toolchain, or run 'backpressure gate' from a detected repo. │
# └───────────────────────────────────────────────────────────────────────────┘`;

function unknownStages(): string {
  return [
    `\necho "== 1. lint =="\npnpm exec biome check . || echo "  (biome not present — tune me)"`,
    `\necho "== 2. typecheck =="\npnpm exec tsc --noEmit || echo "  (tsc not present — tune me)"`,
    `\necho "== 3. test + build =="\npnpm test && pnpm run build`,
  ].join("");
}

function describe(p: StackProfile): string {
  if (p.kind === "rust") return "rust (cargo)";
  if (p.kind === "node")
    return `node (${p.pm ?? "npm"}, runner=${p.testRunner}, linter=${p.linter})`;
  return "unknown";
}

/**
 * Generate a tuned composite gate (bash) for `profile`. Shape is invariant across
 * profiles: shebang, generated marker, `set -euo pipefail`, a secret-scan stage,
 * and a final `gate: GREEN`. Per-language stages differ. `unknown` emits a generic
 * pipeline behind a loud tune-me banner (fail-closed). Pure + deterministic.
 */
export function emitGate(profile: StackProfile): string {
  const banner = profile.kind === "unknown" ? `${UNKNOWN_BANNER}\n` : "";
  const stack = `# Stack: ${describe(profile)}\n`;
  const stages =
    profile.kind === "rust"
      ? rustStages()
      : profile.kind === "node"
        ? nodeStages(profile)
        : unknownStages();
  return `${HEADER}${banner}${stack}${stages}\n${SECRET_SCAN}${GREEN}`;
}
