#!/usr/bin/env bash
# @generated by backpressure gate — edits are overwritten; re-run 'backpressure gate' to retune.
# Composite gate: fail-fast, ONE exit code.
set -euo pipefail

# ┌───────────────────────────────────────────────────────────────────────────┐
# │  ⚠  TUNE THIS GATE TO YOUR STACK. Backpressure could not detect a Rust or    │
# │  Node project, so this is a generic pnpm/TypeScript pipeline. Edit the       │
# │  stages for your toolchain, or run 'backpressure gate' from a detected repo. │
# └───────────────────────────────────────────────────────────────────────────┘
# Stack: unknown

echo "== 1. lint =="
pnpm exec biome check . || echo "  (biome not present — tune me)"
echo "== 2. typecheck =="
pnpm exec tsc --noEmit || echo "  (tsc not present — tune me)"
echo "== 3. test + build =="
pnpm test && pnpm run build

echo "== secret scan =="
if command -v gitleaks >/dev/null 2>&1; then
  gitleaks detect --no-banner --redact
else
  echo "  (gitleaks not installed — skipping secret scan)"
fi

echo "gate: GREEN"
